### ISSUE TITLE
Question: SQL Injection

### ISSUE THREAD

**Issue by ren90** [Davmuz/gqt#7]
Hello,

Pardon my ignorance in case I'm not seeing this right, but if we use parameterized templates in gqt we are vulnerable to SQL injection, right?

Thanks in advance for your help, 
Best regards, 
Renato Vieira

**Comment by Davmuz** [comment]
Hi Renato,
you have to follow the parameter syntax of your database driver in order to be safe from a SQL injection. The template syntax will just help you to construct the queries like placing parameters, joins and so on.

Just a quick example for the pq driver for Postgresql:
```
SELECT id, title, description {{ if join_author }}, authors.name{{ end }}
FROM books
{{ if join_author }}
JOIN authors ON author.id = books.author_id
{{ end }}
WHERE book.id = $1 {{ if is_star_filter }}, books.stars = $2{{ end }}
```
Take a look at the WHERE clause, $1 is the driver's parameter and the {{ if is_star_filter }} is a filter that uses a second driver's parameter.

Pay attention, don't use template parameters like in this example, it's not safe:

`WHERE book.id = {{ .id }}`

**Comment by ren90** [comment]
Yeah indeed, that's what I was talking about, the embedding of  `{{ .SomeAttr }}` approach is not safe, though it would be really interesting if it would. ;)

Thanks for the confirmation!

**Comment by Davmuz** [comment]
You are welcome Renato :)
